# -*- coding: utf-8 -*-
"""avaliacao_victor_D2_ED1_UDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGaJzjOoj-YQdp7KyQ12jPTAsV0pZXpw

Atividade Avaliativa Listas
"""

#1) O que é um dado?
#Dados são conjuntos de números e fatos que são utilizidos para se tornar informações utéis a um algoritmo.

#2) Qual a importância de um algoritmo na área da tecnologia?
#Os algoritmos são uma sequência finita de ações executáveis que visam obter uma solução para um determinado tipo de problema.

#3) Quais são as partes que define um algoritmo?
#Entrada, processamento e saida

#4) Construa um algoritmo que receba uma lista com "cinemas", solicite a um usuário que informe 3 tipos de filmes da área de TI e apresenta quais foram os filmes.
print("Insira 3 filmes relacionados a área de TI a lista 'cinemas'")
print("Insira o primeiro filme")
filme1 = input()
print("Insira o segundo filme")
filme2 = input()
print("Insira o terceiro filme")
filme3 = input()
cinemas=[filme1, filme2, filme3]
print(cinemas)
len(cinemas)

#5) Insira um elemento na lista de animais.
animais=["cat", "dog", "bird"]
animais.insert(0, "fish")
print(animais)

#6) Troque a posição dos elementos no índice [0] para [1].
animais.pop(0)
animais.pop(1)
print(animais)

#7) Apague o primeiro dado da lista.
animais.pop(0)
print(animais)

#8) Informe o maior valor da lista.
max(animais)

#9) Informe o menor valor da lista.
min(animais)

#10) Apague o conteúdo da lista.
animais.clear()
cinemas.clear()
print(animais)
print(cinemas)